### ISSUE TITLE
[Question] Which fonts?

### ISSUE THREAD

**Issue by lonix1** [jayesh-bhoot/enforce-browser-fonts#1]
Another awesome plugin, well done!

Which fonts are used when I override the webpage's fonts? Is this hardcoded or can I set them somehow?

**Comment by JesseTheK** [comment]
Settings -> Language and Appearance -> Advanced lets you define both
- default style (serif or sans serif)
- font for each style (eg, Georgia vs Times or Verdana vs PT Sans)
