### ISSUE TITLE
Multiple browser windows are not handled correctly

### ISSUE THREAD

**Issue by dblsaiko** [jayesh-bhoot/enforce-browser-fonts#10]
The enable state of this seems to be global, so having a browser window with a site that has browser fonts enforced and one that allows website fonts isn't possible, it will always use the state of whichever page was opened last.

**Comment by bhootd** [comment]
I noticed the problem just now...came on github to log the issue, only to see 2 issues already logged for the same problem.

I will get to this asap.

**Comment by bhootd** [comment]
Duplicate of #11
