### ISSUE TITLE
Change fonts when switching sites only

### ISSUE THREAD

**Issue by sojusnik** [jayesh-bhoot/enforce-browser-fonts#3]
When clicking on a link to open it in the background and the new site in the background has a different font setting in your add-on (= main page has enforced fonts and background page doesn't enforce fonts), then the fonts on the main page change as well — they are not enforced any more.

This is irritating and therefore I propose that the fonts should change only when switching sites.

I use "enforce the browser fonts for all sites by default".

**Comment by bhootd** [comment]
Yep. This is a bug.

**Comment by bhootd** [comment]
Fixed in v1.1.
