### ISSUE TITLE
fingerprinting: browser.display.use_document_fonts and RFP

### ISSUE THREAD

**Issue by atomGit** [jayesh-bhoot/enforce-browser-fonts#5]
my understanding is that setting `browser.display.use_document_fonts` to '0' when `privacy.resistFingerprinting` = 'true' actually increases entropy (ability to fingerprint based on installed fonts)

[reference](https://github.com/arkenfox/user.js/issues/1025#issuecomment-702189206)

i'm not sure anything can be done about this, but i wanted to bring it to your attention

**Comment by atomGit** [comment]
actually there may be a possibility here, but it would involve either a re-write or a new extension

i've been setting browser.display.use_document_fonts to '1'  and playing with CSS to set font and size globally, but this is not a viable solution (it would involve a lot of per-site CSS), however, in JQuery (i think it is) there's a `contains` CSS selector thingy, and we can use some RegEx with CSS, so i was thinking of something like this...

```css
*:contains"[a-zA-Z]" {
    font-family: sans-serif;
    font-size: 1em;
}
```

this avoids problems with plain CSS because it would only affect elements that contain text

pre and code, and maybe some other elements, would have to be excluded or overridden

may be a bad idea, but maybe it's something someone can improve upon

**Comment by bhootd** [comment]
I am sorry but what you suggest is quite out of scope of this extension. Seems too much work. :)
