### ISSUE TITLE
Support enforcing font size

### ISSUE THREAD

**Issue by DUOLabs333** [jayesh-bhoot/enforce-browser-fonts#8]
Basically, if the extension is enabled for the site, it uses the browser-mandated minimum font size, otherwise, it enforces no limit.

**Comment by bhootd** [comment]
Firefox exposes only a limited set of configuration APIs to the add-on API. Enforcing font size is not one of them.

Here is the list: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings
