### ISSUE TITLE
enforce-browser-fonts toggles itself on and off

### ISSUE THREAD

**Issue by Karlstens** [jayesh-bhoot/enforce-browser-fonts#9]
This Firefox Extension is great. I've found a bug however, where the extension toggles itself on or off - at random, when loading various websites, whilst having two FireFox browser windows open, one on each screen. 

As a side idea - I think this Extension might work best if it could be URL dependent - where the user specifies a whitelist/blacklist that triggers whether the extension is active or inactive on the destination site by default.

**Comment by bhootd** [comment]
I noticed the problem just now...came on github to log the issue, only to see 2 issues already logged for the same problem.

I will get to this asap.

**Comment by bhootd** [comment]
Duplicate of #11
